<?php

namespace vaersaagod\cloudflaremate\models;

use Craft;
use craft\base\Model;

use vaersaagod\cloudflaremate\records\UriRecord;

/**
 * Url model
 */
class UriModel extends Model
{

    /** @var int */
    public int $siteId;

    /** @var string */
    public string $uri;

    protected function defineRules(): array
    {
        return array_merge(parent::defineRules(), [
            [['uri'], 'string', 'max' => UriRecord::MAX_URI_LENGTH],
        ]);
    }

    /**
     * @param $attributeNames
     * @param $clearErrors
     * @return bool
     */
    public function validate($attributeNames = null, $clearErrors = true)
    {
        $language = Craft::$app->language;
        Craft::$app->language = 'en-US';
        $result = parent::validate($attributeNames, $clearErrors); // TODO: Change the autogenerated stub
        Craft::$app->language = $language;
        return $result;
    }
}
